In [13]:
import numpy as np

In [14]:
a = np.array([1,2,3,4])
a[::2]
a[:2]
print(a.dtype)
a = np.array([12,3,4,5], dtype = float)
print(a)
print(a.dtype)
print([i * 5 for i in a])

int32
[12.  3.  4.  5.]
float64
[60.0, 15.0, 20.0, 25.0]


In [9]:
b = np.array([
    [[1,2,3,4],
     [1,2,5,6]],
    
    [[3,4,6,7],
     [1,3,6,7]],
    
    [[1,2,3,4],
     [1,3,4,5]]
    ])
print(b.shape)
print(b.ndim)
print(b.size)
print(b[2][1][3])   #dim:2, fil:1, col:3
print(b[0, 1, 1])   #dim:0, fil:1, col:1
print(b[0:2])       #dim:0 y 1
print(b[:,0,:])     # de todas las dimensiones traer la fila 0 con todas sis columnas
print("Here")
print(b.sum(axis=2))

(3, 2, 4)
3
24
5
2
[[[1 2 3 4]
  [1 2 5 6]]

 [[3 4 6 7]
  [1 3 6 7]]]
[[1 2 3 4]
 [3 4 6 7]
 [1 2 3 4]]
Here
[[10 14]
 [20 17]
 [10 13]]


In [10]:
c = np.array([
    [1,2,3,4],
    [2,3,4,6],
    [6,8,9,4]
    ])

print(c.sum())
print(c.mean())
print(c.std())
print(c.var())
print(c.sum(axis=0))

52
4.333333333333333
2.3570226039551585
5.555555555555556
[ 9 13 16 14]


In [11]:
d = np.arange(4)
print(d)
print(d + 10)
print(d * 2)
d += 10
print(d)

[0 1 2 3]
[10 11 12 13]
[0 2 4 6]
[10 11 12 13]


In [15]:
e = np.array([1,45,4,75])
f = np.arange(2,6)
print(e+f)

[ 3 48  8 80]


In [25]:
g = np.arange(4)
print(g)
print(g[0], g[-1])
print(g[[0,-1]])
print(g[[True,False,False,True]])
print(g >=2)
print(g[g >=2])
print(g[g > g.mean()])
print(g[~(g > g.mean())])
print(g[(g == 0) | ( g == 3)])
print(g[(g <= 2) & ( g % 2 == 0)])


[0 1 2 3]
0 3
[0 3]
[0 3]
[False False  True  True]
[2 3]
[2 3]
[0 1]
[0 3]
[0 2]


In [32]:
h = np.random.randint(100, size=(3,3))
print(h)
print(h[np.array([
    [True, False, True],
    [False, True, True],
    [True, True, False]
    ])])
print(h > 30)


[[21 43 72]
 [43 91 82]
 [39 94 40]]
[21 72 91 82 39 94]
[[False  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
i = np.random.randint(100, size=(3,3))
print(i)
j = np.random.randint(100, size=(3,2))
print(j)
print(i.dot(j))
print(i @ j)
print(j.T)